### ISSUE TITLE
请问一下31370 这个端口地址在哪里改？找了好久

### ISSUE THREAD

**Issue by aion1998** [w757703598/WQLIdentityServer4#16]
![image](https://user-images.githubusercontent.com/19725014/124237296-f554c100-db49-11eb-94ad-b05fab28fa29.png)

运行报错，如上图

..这3170地址到底在哪呢

**Comment by w757703598** [comment]
没看出来你这日志信息属于那一部分，正常项目中没有这个端口的，都是5000 或者 8000

**Comment by aion1998** [comment]
前面那个错误好像是代理的问题..解决了
然后又冒了个新问题
![image](https://user-images.githubusercontent.com/19725014/124249459-7dd95e80-db56-11eb-8de8-b54fbc96e2b0.png)

为啥我这些样式都404，我已经还原包了

![image](https://user-images.githubusercontent.com/19725014/124250341-62228800-db57-11eb-9fc9-8b07223097e7.png)

**Comment by aion1998** [comment]
> 没看出来你这日志信息属于那一部分，正常项目中没有这个端口的，都是5000 或者 8000

全搞定了。。。但是默认密码是啥，admin 123456 好像不对，试了很多次

**Comment by aion1998** [comment]
啊没事了，在种子数据里看到了
